# This is a basic workflow to help you get started with Actions

name: Deploy FTP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "app" branch
  push:
    branches: [ "app" ]
  pull_request:
    branches: [ "app" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check secrets
        run: |
          env
          echo $FTP_SERVER
          echo $FTP_USERNAME
          echo $FTP_PASSWORD

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: Build NPM project
        run: npm run build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        with:
          server: $FTP_SERVER
          username: $FTP_USERNAME
          password: $FTP_PASSWORD
          local-dir: ./build/static/
          remote-dir: /domains/faerienart.com/public_html/static/

